//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Part3.DbFirstAdvancedMapping
{
    using System;
    
    public enum OrderStatus : byte
    {
        InProcess = 1,
        Approved = 2,
        BackOrdered = 3,
        Rejected = 4,
        Shipped = 5,
        Cancelled = 6
    }
}
