//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Part3.DbFirstAdvancedMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippedOrder : Order
    {
        public System.DateTime ShipDate { get; set; }
    }
}
