//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Part4.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeItem
    {
        public int Id { get; set; }
        public System.DateTime DateAcquired { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual Certification Certification { get; set; }
    }
}
